[project]
name = "kukuvs-superapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "netifaces>=0.11.0",
    "psutil>=7.0.0",
    "screeninfo>=0.8.1",
    "tk>=0.1.0",
]
